### ISSUE TITLE
当column的总宽度大于table宽度时错误

### ISSUE THREAD

**Issue by TianYa-Q** [Ele-Cat/element-expand#5]
当可以横向滚动时，方向箭头会在最右边出现

**Comment by Ele-Cat** [comment]
注意将 type="expand" 的 width="1" 设置一下就可以了

**Comment by TianYa-Q** [comment]
这样子设置在columns的总宽度等于table的时候是可以的，但是当宽度大于table时，也就是出现横向滚动条时，就会出现bug
  .el-table__expand-column {
    display: none;
  }
我是这样设置解决的
